### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by lirunkai** [indooorsman/angular-twitter#1]

**Comment by indooorsman** [comment]
报错信息贴出来…

**Comment by lirunkai** [comment]
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "./dist" is not an absolute path!

**Comment by lirunkai** [comment]
解决了
 let path = require('path');
 output: {
    path: path.resolve(__dirname,'dist')
}

**Comment by indooorsman** [comment]
webpack的版本号看一下

**Comment by lirunkai** [comment]
2.3.2

**Comment by indooorsman** [comment]
我写这部分代码的时候webpack用的2.2.1，新版本按报错的信息应该是只能写绝对路径了，回头我升级webpack再测试下

**Comment by indooorsman** [comment]
fixed
